version: '3'

services:
  nginx:
    build: ./nginx
    depends_on:
      - api
      - next
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - /etc/letsencrypt/live/code-directory.com/fullchain.pem:/etc/nginx/cert/fullchain.pem
      - /etc/letsencrypt/live/code-directory.com/privkey.pem:/etc/nginx/cert/privkey.pem
    environment:
      - NEXTJS_CONTAINER_IP=next # supplying environment vars

  api:
    build: ./api
    # restart: always
    ports:
      - '5000:5000'
    depends_on:
      - postgres

  next:
    build: ./next
    # restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports: 
      - '5433:5432'
    volumes:
      - ./CD-DataBase.sql:/docker-entrypoint-initdb.d/CD-DataBase.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: codedirectory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 23400
volumes:
  postgres_data: